import images from './images'

export const contacts = [
    {
        id: '1',
        userName: 'The Myth Buster',
        userImg: images.user1,
        isOnline: false,
        lastSeen: '3 hours ago',
        lastMessage: 'The misconception or limiting belief',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '2',
        userName: 'Truth vs Trend',
        userImg: images.user2,
        isOnline: true,
        lastSeen: '4 hours ago',
        lastMessage: 'Addressing alternatives',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '3',
        userName: 'Triumph of the Spirit',
        userImg: images.user3,
        isOnline: false,
        lastSeen: '2 days ago',
        lastMessage: "Stir up something in your audience they didn't know was there",
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '4',
        userName: 'Agent of Change',
        userImg: images.user4,
        isOnline: true,
        lastSeen: '3 days ago',
        lastMessage: 'Immediately influence the way your audience thinks about something',
        messageInQueue: 0,
        sentDate: 'Today',
    },
    {
        id: '5',
        userName: 'The Negotiator',
        userImg: images.user5,
        isOnline: false,
        lastSeen: '5 days ago',
        lastMessage: 'Convince your audience to take action',
        messageInQueue: 0,
        sentDate: '23/9',
    },
    {
        id: '6',
        userName: 'Mr Arik Tsur',
        userImg: images.user6,
        isOnline: true,
        lastSeen: '6 days ago',
        lastMessage: 'You will be working with the best in the game. Enough said.',
        messageInQueue: 3,
        sentDate: 'Today',
    },
    {
        id: '7',
        userName: 'Mr Arik Tsur',
        userImg: images.user6,
        isOnline: true,
        lastSeen: '1 week ago',
        lastMessage: 'You will be working with the best in the game. Enough said.',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '8',
        userName: 'Truth vs Trend',
        userImg: images.user2,
        isOnline: true,
        lastSeen: '2 weeks ago',
        lastMessage: 'Addressing alternatives',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '9',
        userName: 'Truth vs Trend',
        userImg: images.user2,
        isOnline: true,
        lastSeen: '2 weeks ago',
        lastMessage: 'Addressing alternatives',
        messageInQueue: 3,
        sentDate: '12/7',
    },
]
